### ISSUE TITLE
Could you add support for https://epsg.io/5514?

### ISSUE THREAD

**Issue by JunkMeal** [wroge/wgs84#3]
The title says it, I want to convert https://epsg.io/5514 to WGS84 and this library seemed promising, but it looks like it doesnt support it

**Comment by wroge** [comment]
I haven't yet implemented the Krovak projection. Is this the correct formula? https://epsg.io/9819-method   
You can try to implement the [Projection interface](https://github.com/wroge/wgs84/blob/main/interface.go#LL26C9), then it should be quite easy to create the coordinate reference system. I would be very happy about a pull request. Otherwise I can try to implement it as soon as I have some time.

**Comment by JunkMeal** [comment]
Thanks for your quick response! To be honest I am not really knowledgeable in coordinates. I just wanted to use some of my cities geo data and it uses the S-JTSK coordinates. I don't know if that is the correct formula. I could try implementing the Projection interface, but as I said I am not very familiar with this.

**Comment by wroge** [comment]
I have added your EPSG code. Warning: The v2 API is still WIP and can change at any time.

```sh
go get github.com/wroge/wgs84/v2
```

**Comment by wroge** [comment]
```go
transform := wgs84.Transform(wgs84.EPSG(4326), wgs84.EPSG(5514))

east, north, h := transform(20, 50, 0)

fmt.Println(east, north, h)
// -346236.0526298934 -1.092469745978949e+06 -39.299266709946096
```

**Comment by JunkMeal** [comment]
Thanks!
